lib/go_barber_web/router.ex
defmodule GoBarberWeb.Router do
  use GoBarberWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {GoBarberWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug GoBarberWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", GoBarberWeb do
    pipe_through :browser

    get "/", Redirect, to: "/signin"

    live "/signin", SessionLive.New

    post "/session", SessionController, :create
    delete "/session", SessionController, :delete

    get "/signup", UserController, :new
    post "/signup", UserController, :create

    get "/provider", ProviderController, :index
    get "/customer", CustomerController, :index

    live "/profile", ProfileLive, :index
  end

  scope "/provider", GoBarberWeb do
    pipe_through [:browser, :authenticate_user, :requires_provider]

    live "/dashboard", ProviderLive.Dashboard, :index
  end

  scope "/customer", GoBarberWeb do
    pipe_through [:browser, :authenticate_user, :requires_customer]

    live "/dashboard", CustomerLive.Dashboard, :index
    live "/appointments/new", CustomerLive.Appointments.New, :new
  end

  # Other scopes may use custom stacks.
  scope "/api", GoBarberWeb.API, as: :api do
    pipe_through :api

    post "/users", UserController, :create
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/live_dashboard", metrics: GoBarberWeb.Telemetry
    end
  end
end

lib/go_barber/accounts/user.ex
defmodule GoBarber.Accounts.User do
  use Ecto.Schema
  import Ecto.Changeset
  alias GoBarber.Schedules.Appointment

  @possible_roles ~w(customer provider)

  @required_attrs ~w(name email user_role)a
  @optional_attrs ~w(avatar)a

  @primary_key {:id, :binary_id, autogenerate: true}
  schema "users" do
    field :name, :string
    field :email, :string
    field :avatar, :string
    field :user_role, :string
    field :password, :string, virtual: true
    field :password_hash, :string

    has_many :appointments_as_customer, Appointment, foreign_key: :customer_id
    has_many :appointments_as_provider, Appointment, foreign_key: :provider_id

    timestamps()
  end

  def changeset(user, attrs) do
    user
    |> cast(attrs, @required_attrs ++ @optional_attrs)
    |> validate_required(@required_attrs)
    |> validate_format(:email, ~r/@/)
    |> unique_constraint(:email)
  end

  def registration_changeset(user, attrs) do
    user
    |> changeset(attrs)
    |> cast(attrs, [:password])
    |> validate_required([:password])
    |> validate_length(:password, min: 8)
    |> validate_inclusion(:user_role, @possible_roles)
    |> put_pass_hash()
  end

  defp put_pass_hash(%Ecto.Changeset{valid?: true, changes: %{password: pass}} = changeset) do
    change(changeset, Argon2.add_hash(pass))
  end

  defp put_pass_hash(invalid_changeset), do: invalid_changeset

  def profile_changeset(user, attrs) do
    user
    |> cast(attrs, [:name, :email])
    |> validate_required([:name, :email])
    |> validate_format(:email, ~r/@/)
    |> unsafe_validate_unique(:email, GoBarber.Repo)
    |> unique_constraint(:email)
  end

  def avatar_changeset(user, avatar) do
    user
    |> cast(avatar, [:avatar])
    |> validate_required([:avatar])
  end

  def password_changeset(user, attrs, opts \\ []) do
    user
    |> cast(attrs, [:password])
    |> validate_required([:password])
    |> validate_confirmation(:password)
    |> validate_length(:password, min: 8)
    |> maybe_hash_password(opts)
  end

  defp maybe_hash_password(changeset, opts) do
    hash_password? = Keyword.get(opts, :hash_password, true)
    password = get_change(changeset, :password)

    if hash_password? && password && changeset.valid? do
      changeset
      |> put_change(:password_hash, Argon2.hash_pwd_salt(password))
      |> delete_change(:password)
    else
      changeset
    end
  end

  def validate_current_password(changeset, password) do
    if valid_password?(changeset.data, password) do
      changeset
    else
      add_error(changeset, :current_password, "is not valid")
    end
  end

  defp valid_password?(%GoBarber.Accounts.User{password_hash: password_hash}, password)
       when is_binary(password) and byte_size(password) > 0 do
    Argon2.verify_pass(password, password_hash)
  end

  defp valid_password?(_, _) do
    Argon2.no_user_verify()
    false
  end
end

lib/go_barber_web/controllers/api/user_controller.ex
defmodule GoBarberWeb.API.UserController do
  use GoBarberWeb, :controller

  alias GoBarber.Accounts

  action_fallback GoBarberWeb.FallbackController

  def create(conn, user_params) do
    with {:ok, user} <- Accounts.register_user(user_params) do
      conn
      |> put_status(201)
      |> render("create.json", user: user)
    end
  end
end

lib/go_barber_web/controllers/user_controller.ex
defmodule GoBarberWeb.UserController do
  use GoBarberWeb, :controller

  alias GoBarber.Accounts
  alias GoBarber.Accounts.User
  alias GoBarberWeb.Auth

  def create(conn, %{"user" => user_params}) do
    case Accounts.register_user(user_params) do
      {:ok, user} ->
        conn
        |> Auth.login(user)
        |> redirect_by_user_role(user)

      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def new(conn, _params) do
    changeset = Accounts.change_registration(%User{}, %{})
    render(conn, "new.html", changeset: changeset)
  end
end

lib/go_barber_web/views/user_view.ex
defmodule GoBarberWeb.UserView do
  use GoBarberWeb, :view

  alias GoBarberWeb.ComponentLive
  alias GoBarberWeb.UserLive
end

lib/go_barber_web/templates/user/form_new.html.leex
<%= f = form_for(@changeset, Routes.user_path(@socket, :create),
          phx_change: "change",
          class: "text-gray-hard w-80 px-4 sm:px-0"
        ) %>

<div class="text-center mt-20 mb-12 space-x-6 font-medium">
  <%= label class: "#{
              if @user_role == "customer",
                do: "text-white pb-2 border-b-2 border-orange",
                else: "cursor-pointer hover:text-gray"
            } transition-colors duration-300" do %>
  Customer
  <%= radio_button f, :user_role, "customer", class: "hidden", checked: true %>
  <% end %>

  <%= label class: "#{
              if @user_role == "provider",
                do: "text-white pb-2 border-b-2 border-orange",
                else: "cursor-pointer hover:text-gray"
            } transition-colors duration-300" do %>
  Provider
  <%= radio_button f, :user_role, "provider", class: "hidden" %>
  <% end %>
</div>

<div class="mb-2">
  <%= live_component(
        @socket,
        ComponentLive.Input,
        id: "name-input",
        f: f,
        icon: "user",
        field: :name,
        input: [
          placeholder: "Name",
          value: input_value(f, :name)
        ]
      ) %>
</div>
<div class="mb-2">
  <%= live_component(
        @socket,
        ComponentLive.Input,
        id: "email-input",
        f: f,
        icon: "mail",
        field: :email,
        input: [
          placeholder: "E-mail",
          value: input_value(f, :email)
        ]
      ) %>
</div>
<div>
  <%= live_component(
        @socket,
        ComponentLive.Input,
        id: "pass-input",
        f: f,
        icon: "lock",
        field: :password,
        input: [
          placeholder: "Password",
          type: "password",
          value: input_value(f, :password)
        ]
      ) %>
</div>

<%= submit "Sign Up", class: "mt-6 bg-orange text-inputs w-full py-4
                                rounded-lg hover:opacity-80 transition-all
                                duration-200 font-medium" %>
</form>

lib/go_barber_web/templates/user/new.html.eex
<div class="flex h-screen bg-background">
  <div class="hidden md:block bg-sign-up bg-center bg-cover bg-no-repeat h-full w-full"></div>

  <div class="flex flex-col justify-center items-center w-full max-w-3xl">
    <img src="<%= Routes.static_url(@conn, "/images/logo.svg") %>" alt="Logo">

    <%= live_render @conn, UserLive.FormNew, session: %{"changeset" => @changeset} %>

    <%= link to: "/signin",
              class: "text-white mt-20 transition-all duration-200 hover:opacity-70" do %>
    <span class="flex items-center">
      <%= fi_icon "arrow-left", class: "w-5 h-5 mr-2 text-white" %>
      Sign In
    </span>
    <% end %>
  </div>
</div>

lib/go_barber_web/templates/user/new.html.leex
<div class="flex h-screen bg-background">
  <div class="bg-sign-up bg-center bg-cover bg-no-repeat h-full w-full mix-blend-hard-light"></div>

  <div class="flex flex-col justify-center items-center w-full max-w-3xl">
    <img src="<%= Routes.static_url(@socket, "/images/logo.svg") %>" alt="Logo">

    <%= render "form_new.html", assigns %>

    <%= link to: "/signin",
              class: "text-white mt-20 transition-all duration-200 hover:opacity-70" do %>
    <span class="flex items-center">
      <%= fi_icon "arrow-left", class: "w-5 h-5 mr-2 text-white" %>
      Fazer login
    </span>
    <% end %>
  </div>
</div>